"""
Pytest configuration and fixtures for arff_csv tests.
"""

from __future__ import annotations

from pathlib import Path
from typing import Generator

import pandas as pd
import pytest


@pytest.fixture
def sample_arff_content() -> str:
    """Sample ARFF file content for testing."""
    return """% Sample ARFF file for testing
% Generated by arff-csv-converter

@RELATION iris

@ATTRIBUTE sepallength NUMERIC
@ATTRIBUTE sepalwidth NUMERIC
@ATTRIBUTE petallength NUMERIC
@ATTRIBUTE petalwidth NUMERIC
@ATTRIBUTE class {Iris-setosa, Iris-versicolor, Iris-virginica}

@DATA
5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
7.0,3.2,4.7,1.4,Iris-versicolor
6.4,3.2,4.5,1.5,Iris-versicolor
6.3,3.3,6.0,2.5,Iris-virginica
5.8,2.7,5.1,1.9,Iris-virginica
"""


@pytest.fixture
def sample_arff_with_missing() -> str:
    """Sample ARFF file with missing values."""
    return """@RELATION test_missing

@ATTRIBUTE a NUMERIC
@ATTRIBUTE b STRING
@ATTRIBUTE c {yes, no}

@DATA
1.0,hello,yes
?,world,no
3.0,?,yes
4.0,test,?
"""


@pytest.fixture
def sample_arff_with_strings() -> str:
    """Sample ARFF file with string attributes."""
    return """@RELATION strings_test

@ATTRIBUTE id INTEGER
@ATTRIBUTE name STRING
@ATTRIBUTE description STRING

@DATA
1,'John Doe','A person with spaces'
2,"Jane's name","Description with, comma"
3,Simple,NoSpaces
"""


@pytest.fixture
def sample_arff_sparse() -> str:
    """Sample ARFF file with sparse data."""
    return """@RELATION sparse_test

@ATTRIBUTE a NUMERIC
@ATTRIBUTE b NUMERIC
@ATTRIBUTE c NUMERIC
@ATTRIBUTE d NUMERIC

@DATA
{0 1.0, 2 3.0}
{1 2.0, 3 4.0}
{0 5.0, 1 6.0, 2 7.0, 3 8.0}
"""


@pytest.fixture
def sample_arff_date() -> str:
    """Sample ARFF file with date attributes."""
    return """@RELATION dates_test

@ATTRIBUTE event_date DATE 'yyyy-MM-dd'
@ATTRIBUTE value NUMERIC

@DATA
'2024-01-15',100
'2024-02-20',200
'2024-03-25',300
"""


@pytest.fixture
def sample_dataframe() -> pd.DataFrame:
    """Sample DataFrame for testing CSV to ARFF conversion."""
    return pd.DataFrame({
        "id": [1, 2, 3, 4, 5],
        "name": ["Alice", "Bob", "Charlie", "Diana", "Eve"],
        "age": [25, 30, 35, 28, 32],
        "score": [85.5, 92.3, 78.9, 88.1, 95.0],
        "passed": pd.Categorical(["yes", "yes", "no", "yes", "yes"]),
    })


@pytest.fixture
def sample_dataframe_with_missing() -> pd.DataFrame:
    """Sample DataFrame with missing values."""
    import numpy as np
    
    return pd.DataFrame({
        "a": [1.0, np.nan, 3.0, 4.0],
        "b": ["hello", "world", np.nan, "test"],
        "c": pd.Categorical(["yes", "no", "yes", np.nan]),
    })


@pytest.fixture
def temp_dir(tmp_path: Path) -> Path:
    """Provide a temporary directory for file operations."""
    return tmp_path


@pytest.fixture
def sample_csv_file(temp_dir: Path, sample_dataframe: pd.DataFrame) -> Path:
    """Create a sample CSV file for testing."""
    csv_path = temp_dir / "sample.csv"
    sample_dataframe.to_csv(csv_path, index=False)
    return csv_path


@pytest.fixture
def sample_arff_file(temp_dir: Path, sample_arff_content: str) -> Path:
    """Create a sample ARFF file for testing."""
    arff_path = temp_dir / "sample.arff"
    arff_path.write_text(sample_arff_content, encoding="utf-8")
    return arff_path
